### ISSUE TITLE
Forgotten dependency

### ISSUE THREAD

**Issue by tarampampam** [spector517/3proxy-ansible-role#1]
Looks like a forgotten additional dependency 😃 

```text
ERROR! couldn't resolve module/action 'make'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/.ansible/roles/spector517.proxy3/tasks/main.yml': line 39, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Compile sources
  ^ here
```

https://github.com/spector517/3proxy-ansible-role/blob/92bc514435a63f0fb61f4b6b16f66ca466c387d1/tasks/main.yml#L39-L43

ps. Anyway, thx for your role!

**Comment by spector517** [comment]
@tarampampam Thank you for feedback!
The 'make' module maintained by Ansible community and included in Ansible (2.5+).
It's strange that you are getting the error.

Anyway, I will update the README =)
